# Refresh r2u build for arm64

name: docker

on:
  #push:
  #pull_request:
  #release:
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        config:
          - { ver: '20.04', tag: 'focal', cpu: 'amd64', runs: 'ubuntu-20.04' }
          - { ver: '22.04', tag: 'jammy', cpu: 'amd64', runs: 'ubuntu-22.04' }
          - { ver: '24.04', tag: 'noble', cpu: 'amd64', runs: 'ubuntu-24.04' }
          - { ver: '24.04', tag: 'noble', cpu: 'arm64', runs: 'ubuntu-24.04-arm' }

    name: '24.04 (arm64)'

    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: noble
          tags: rocker/r2u:24.04,rocker/r2u:noble
