## Dual build:
##  - once in (focal,jammy) matrix for amd64 only, and
##  - once (noble) for a dual-platform (arm64, amd64)

name: docker

on:
  #push:
  #pull_request:
  #release:
  workflow_dispatch:

jobs:
  dual-platform:
    runs-on: ubuntu-latest
    name: 24.04 (dual-platform)
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        no-cache: true
        platforms: linux/amd64,linux/arm64
        context: noble
        tags: rocker/r2u:noble,rocker/r2u:24.04,rocker/r2u:latest
    
  matrix:
    runs-on: ${{ matrix.config.runs }}
    name: '${{ matrix.config.ver }} (${{ matrix.config.cpu }})'
    strategy:
      fail-fast: false
      matrix:
        config:
          - { ver: '20.04', tag: 'focal', cpu: 'amd64', runs: 'ubuntu-20.04' }
          - { ver: '22.04', tag: 'jammy', cpu: 'amd64', runs: 'ubuntu-22.04' }
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    #- name: Set up QEMU
    #  uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        no-cache: true
        context: ${{ matrix.config.tag }}
        tags: rocker/r2u:${{ matrix.config.ver }},rocker/r2u:${{ matrix.config.tag }}
